workflows:
    ios-workflow:
      name: iOS Workflow
      environment:
        groups:
          - app_store_credentials # <-- (APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
        vars:
          XCODE_WORKSPACE: "VideoMaker.xcworkspace" # <-- Put the name of your workspace here.
          XCODE_SCHEME: "VideoMaker" # <-- Put the name of your scheme here.
          BUNDLE_ID: "com.michaeldunn.pika" # <-- Put your Bundle Id here.
          APP_STORE_APP_ID: 6761820559 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
          #APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
          #APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
          #APP_STORE_CONNECT_PRIVATE_KEY: "$APP_STORE_CONNECT_PRIVATE_KEY"
          #CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY
        xcode: 26.1.1
        cocoapods: 1.16.2
      scripts:
        - name: Test echo
          script: |
            echo $APP_STORE_CONNECT_ISSUER_ID
            echo $APP_STORE_CONNECT_KEY_IDENTIFIER
            echo $APP_STORE_CONNECT_PRIVATE_KEY
            echo $CERTIFICATE_PRIVATE_KEY
        - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
          script: |
            keychain initialize
        - name: Fetch signing files
          script: |
            app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
        - name: Use system default keychain
          script: |
            keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Change Bundle ID for release
          script: |
            new_bundle_id=$BUNDLE_ID
            project=$(ls | grep .xcodeproj)
            old_bundle_id=$(awk -F '=' '/PRODUCT_BUNDLE_IDENTIFIER/ {print $2; exit}' ./"$project"/project.pbxproj)
            old_bundle_id=${old_bundle_id:0:$((${#old_bundle_id} - 1))}
            sed -i '' "s/${old_bundle_id}/${new_bundle_id}/g" ./"$project"/project.pbxproj
        - name: Increment build number
          script: |
            #!/bin/sh
            set -e
            set -x
            cd $FCI_BUILD_DIR
            agvtool new-version -all $(($BUILD_NUMBER + 1))
        - name: Cocoapodsv
          script: |
            #!/bin/sh
            pod install
        - name: Build ipa for distribution
          script: |
            xcode-project use-profiles
            xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME" \
              --archive-flags "-destination 'generic/platform=iOS'" \
              --archive-xcargs "CODE_SIGNING_REQUIRED=YES CODE_SIGNING_ALLOWED=YES" \
              --verbose
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution
            api_key: $APP_STORE_CONNECT_PRIVATE_KEY         # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
            key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
            issuer_id: $APP_STORE_CONNECT_ISSUER_ID         # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
            submit_to_testflight: false                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
            # beta_groups:                                  # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
            #       - group name 1
            #       - group name 2
